const UserActionTypes = {
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_ERROR: 'SET_ERROR',
}

export default UserActionTypes